Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -332,7 +332,7 @@ jobs:
              --output text )
             export API_URL=http://${BACKEND_IP}:3030
             echo "${API_URL}"
-            if curl -s ${API_URL}/api/status -v | grep "ok"
+            if curl -s $API_URL/api/status | grep "ok"
             then
               exit 0
             else
@@ -345,11 +345,12 @@ jobs:
             echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
-              exit 0
+              exit 1 # will convert it to 0 after failure 
             else
               exit 1
             fi      
-
+      - destroy_environment      
+      - revert-migrations  
 
   cloudfront-update:
     docker:
@@ -371,7 +372,8 @@ jobs:
                     --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
                     --region us-east-1 \
                     --tags project=udapeople
-
+      - destroy_environment      
+      - revert-migrations  
 workflows:
   build-udacity-p3-workflow:
     jobs:
